#  ************ 【系统设置】 ************* 
#  渲染精细度，可选值50~200，建议100。设置高精度会提高图片的精细度，但因图片较大可能会影响渲染与发送速度
renderScale: 100

#  渲染质量 可选值50~100
randerQuality: 100

#  渲染大小 可选任意值
b19size: 50

#  ************ 【发送设置】 ************* 

#  是否开启频道模式（文字版仅限私聊，关闭文字版图片，文字版将折叠为一条消息，把@改为回复）
isGuild: false

#  文字版b19是否带图，关闭可以节约大量发送时间
WordB19Img: true

#  文字版suggest是否带图，关闭可以节约大量发送时间
WordSuggImg: true

#  ************ 【接收设置】 ************* 
#  命令头
cmdhead: "phi"

#  ************ 【娱乐设置】 ************* 
#  猜曲绘提示时间间隔(s)
GuessTipCd: 15

#  猜字母群聊全局猜测冷却时间间隔(s)
LetterGuessCd: 3

#  猜字母群聊全局翻开字母冷却时间间隔(s)
LetterRevealCd: 12

#  猜字母群聊全局提示冷却时间间隔(s)
LetterTipCd: 30

#  猜曲绘是否撤回
GuessTipRecall: false

#  猜字母题面是否公布猜对者
LetterWinner: false